### ISSUE TITLE
Problems with iPhone Xs Max

### ISSUE THREAD

**Issue by Biornne** [hemantasapkota/goplayground#1]
Hi.

You have done a great work with your app. Congratulations, it’s awesome. I’m playing with that in some time and I love it. I noticed couple problems with iPhone XS Max though (which I personally have). When I’m editing something in code, after first run, than, window is showing up with error (done button and layout is broken). Can that be fixed? Layout on iPhone XS isn’t great, but it works though. Last thing is editing code - I can’t edit code inside of statement, I can do that after the sentence only - It’s looks like the magnifying loupe doesn’t work, the same with editing with 3D Touch (when keyboard can turn into a trackpad, and changing text with cursor). I know that it’s lot of thing, but please can you fix this? I pretty sure that everyone would pay for your app, because is great idea, much more handy that anything else on the App Store. 

Thank’s

**Comment by hemantasapkota** [comment]
Thanks for the feedback @Biornne. I really appreciate it.

Can you send a screenshot for the layout issue ? It'd help me understand the issue better.

Comments on rest of the issues:

1. **Can't edit code inside of statement** - This is a high-priority issue for me.

2. **Layout for iPhone XS**  - I'll test it on the simulator.

3. **Magnifying Loupe** - In edit mode, if you long-press, magnifying loupe gets enabled. Can you try this ?

4. **"the same with editing with 3D Touch (when keyboard can turn into a trackpad, and changing text with cursor)"** - Can you clarify ?

**Comment by Biornne** [comment]
Ok, below different screenshots:

**Layout issue** 
This is when, I'm editing code first time: 
![first_run1](https://user-images.githubusercontent.com/27034831/51385300-23332000-1b1f-11e9-8533-320abbe57722.png)

**Layout issue** 
(Bellow) That is when I want to edit code after first run:

![second_run](https://user-images.githubusercontent.com/27034831/51385303-23cbb680-1b1f-11e9-989b-ef802271d898.png)

**2. Layout for iPhone XS**
(Bellow) Layout problem with top and bottom margins (but it's very little problem)

![layout1](https://user-images.githubusercontent.com/27034831/51385301-23cbb680-1b1f-11e9-9c00-8d62ca9c7995.png)

**3. Magnifying Loupe**
Magnifying loupe problem. See where the magnifying loupe and where the cursor is? Normally, the cursor should be in the middle of the magnifier in order to be able to edit the code.

![magnifying_loupe](https://user-images.githubusercontent.com/27034831/51385302-23cbb680-1b1f-11e9-88c3-9e8df3bdc062.png)

**4. Editing with 3D Touch**
Sample video - https://www.youtube.com/watch?v=ufHFnbv4NdI
It would be great to have such functionality to edit the code.
ps. the video is not mine ;)

**Comment by hemantasapkota** [comment]
Hi, 

I think I've fixed the layout issues you've been facing. 

Can you update the app and check if it's working ?

Thanks

**Comment by Biornne** [comment]
Yes, now it’s working great! Awesome, wonderful work!
Thank you very much :)

**Comment by hemantasapkota** [comment]
Great!! Closing this.
